### ISSUE TITLE
Add Russian language translation

### ISSUE THREAD

**Issue by TechHummel** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#141]
See #119

**Comment by carawan** [comment]
Thanks!

**Comment by TechHummel** [comment]
@rowysock Do you think we can create a Github organization for this integration? I hope that this might speed up development and maybe also attract other developers :)

**Comment by rowysock** [comment]
@TechHummel I've created an organization. You have an invite pending

**Comment by TechHummel** [comment]
Thanks for that! 👍 
I wanted to create a new tag for a beta release (mainly so that I can ask people to test if bugs still occur with the latest version), howver, I am receiving a “You're not authorized to create a tag" error.

**Comment by rowysock** [comment]
Made you an owner. Have fun :)
