### ISSUE TITLE
Can't add cloud device 

### ISSUE THREAD

**Issue by fuzunspm** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#147]
I'm having an issue after selecting the device from cloud with an error message of

Logger: homeassistant.setup
Source: setup.py:278
First occurred: 10:20:52 PM (1 occurrences)
Last logged: 10:20:52 PM

Setup failed for custom integration homewhiz: No setup or config entry setup function defined.

**Comment by TechHummel** [comment]
Without more logs or more information about the Homewhiz device, we are unable to help you 😢
