### ISSUE TITLE
Update Turkish translation

### ISSUE THREAD

**Issue by teqali** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#150]
https://github.com/rowysock/home-assistant-HomeWhiz/blame/72fc43e984b92907f2b4dfef9168a16aaaffc4e1/custom_components/homewhiz/translations/tr.json#L24

"Devlet" is false.
"Durum" true

**Comment by teqali** [comment]
> Thanks for pointing this out! This needs to be the translation for the English word "state" though. Would "Eyalet" work?

State=Durum

**Comment by TechHummel** [comment]
Thanks, could you just confirm that this is correct: https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/196
