### ISSUE TITLE
Refrigerator Support

### ISSUE THREAD

**Issue by teqali** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#151]
Hello there,
I have a  Beko refrigerator. It seems to be integrated via HomeWhiz app. Does this addon integrate refrigerators?

**Comment by TechHummel** [comment]
Hi!
That's a good question, and I honestly don't know – have you tried setting it up with the integration?
Also, please include your device digital ID, thanks!

**Comment by TechHummel** [comment]
I'll close this issue for now. Without any testing of users with a fridge as well as logs in case fridges are not working, there is nothing we can do.
