### ISSUE TITLE
Arcelik Gurme is not working (no device found)

### ISSUE THREAD

**Issue by Kilicco** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#155]
When connecting the tea maker, the message: no devices found in the network occurs.
All steps for Bluetooth as indicated in the manual have been completed.

**Comment by TechHummel** [comment]
Thanks for reporting this issue! 👍 
Could you please test if this issue still occurs with the latest beta release? Thanks!

**Comment by TechHummel** [comment]
@onuryilmazdev Please use English only.

**Comment by onuryilmazdev** [comment]
the problem continue. I tested it in beta version

**Comment by kaancanerkut** [comment]
Same with Arçelik Gurme TeaMaker.

1-I installed homewhiz HA
2- login with cloud 
3- integration found the device
4-when i clicked submit it says Unknown Error Occured

**Comment by kaancanerkut** [comment]
![Screenshot_2024-02-21-16-52-13-912_com homewhiz global](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/154026440/eaa310b8-9483-4671-9e2d-7e20a349017c)

**Comment by sarpdoruk** [comment]
See my comment [here](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues/173#issuecomment-1967580515) for the instructions.

**Comment by TechHummel** [comment]
Since this is a duplicate, I will close the issue 😃
