### ISSUE TITLE
homewhiz makes home assisant restart too slow

### ISSUE THREAD

**Issue by cnecrea** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#159]
Hi there,

After I've installed homewhiz on home assistant with bluetooth connection via ESP32 my home assistant works slowly. If i restart HA it tooks five minutes to load it.

Any solution?

**Comment by cnecrea** [comment]
I got this error on HA:

Logger: py.warnings
Source: custom_components/homewhiz/bluetooth.py:54
Integration: HomeWhiz ([documentation](https://github.com/rowysock/home-assistant-HomeWhiz), [issues](https://github.com/rowysock/home-assistant-HomeWhiz/issues))
First occurred: 15:20:03 (1 occurrences)
Last logged: 15:20:03

/config/custom_components/homewhiz/bluetooth.py:54: FutureWarning: BLEDevice.rssi is deprecated and will be removed in a future version of Bleak, use AdvertisementData.rssi instead _LOGGER.info(f"Successfully connected. RSSI: {self._device.rssi}")

**Comment by TechHummel** [comment]
Thanks for reporting this issue 👍 
Can you please include more information? E.g., home-assistant version, server hardware, homewhiz device, esphome version, etc?
Could you please test with the latest beta release and let us know if the behaviour changed?

**Comment by cnecrea** [comment]
For days I have been testing versions and among other things the WIFI network and Bluetooth.

Currently, I use the Home Assistant OS with this version:

Home Assistant 2023.10.5
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

HiLetgo ESP-WROOM-32 ESP32 ESP-32D Development Board 2.4GHz Dual-Mode WiFi + Bluetooth Dual Cores Microcontroller Processor Integrated with Antenna RF AMP Filter Ap STA for Arduino IDE:
LINK: https://shorturl.at/cuzJP

My washing machine is: BEKO B5WFU78435WB (7002340002)

My computer where I run the Home Assistant is:
HP T630 Thin Client, 4x 2.2GHz CPU, 8 GB DDR4, 128 GB M.2 NVME SSD

I have tested all versions (available for download in HACS) and the result is all the same.
If I configure HomeWhiz to run through the Cloud, I don't have any problems. But through Bluetooth, yes, I have this problem.

Restarting the HA with HomeWhiz configured via Bluetooth takes between 3:30 and 5 minutes.
I have tried moving the HA and the network just one meter from the washing machine, the result is the same.
I should be remark that there is no signal saturation or other Wi-Fi networks in my apartment or nearby.

Without a doubt, the problem starts when I configure the washing machine through Bluetooth. When I finish configuring it and restart the HA, it takes a long time to restart.

I've tested the 0.50 (beta one), the result is the same.

What should I do?

**Comment by TechHummel** [comment]
Thanks for the feedback and for testing again. I'm not sure what to do, to be honest 😢 
I am not sure what could be causing this integration to slow down homeassistant by this much. Maybe some other people are experiencing the same issue? I connect via Bluetooth and my homeassistant starts quickly.

**Comment by cnecrea** [comment]
> Thanks for the feedback and for testing again. I'm not sure what to do, to be honest 😢 I am not sure what could be causing this integration to slow down home assistant by this much. Maybe some other people are experiencing the same issue? I connect via Bluetooth and my home assistant starts quickly.

@TechHummel, somehow but I don't even know what happened, it has started working correctly, it doesn't take long to restart. Right now if I restart the HA, it takes at most 20 seconds, which is acceptable and normal.

By the way, can you tell me how to create a task to remotely "start" the already selected program from HA?

**Comment by TechHummel** [comment]
Great to hear! I haven't experimented with that yet, to be honest. 
Is this supported via the remote control? Else, it might be disabled for security.

**Comment by cnecrea** [comment]
Yes, from the HomeWhiz app I can start the program. The only thing I have to do first is put the program in "Downloaded program" mode and press the "remote control" button

![IMG_0397](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/48139709/fee99243-3055-498c-9861-7a81b522cc01)
![IMG_0398](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/48139709/6ce13957-be8e-4ad1-b270-b994acff3568)
![IMG_0399](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/48139709/f03f2eda-eb23-48c4-860c-2298a3bb662a)

**Comment by cnecrea** [comment]
@TechHummel, have you been able to find out anything regarding the previous question?
