### ISSUE TITLE
Failure to configure integration

### ISSUE THREAD

**Issue by EinSchwerd** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#174]
When I try to install this integration through the cloud I receive a failure with the following in the logs:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
    return await setup_cloud(entry, hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
    _lazy_install_awsiotsdk()
  File "/config/custom_components/homewhiz/__init__.py", line 71, in _lazy_install_awsiotsdk
    if not is_installed(pkg) and not install_package(pkg, find_links=links):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: install_package() got an unexpected keyword argument 'find_links'`

**Comment by PeteCooney** [comment]
Getting the same thing here. Re-downloading the integration (v0.5.1-beta) seems to have fixed the issue for me though so might be worth giving that a try?

**Comment by elektrolitr** [comment]
This issue is the same as #169 and it's solved in the (v0.5.1-beta) 

I think this one can be closed.

**Comment by TechHummel** [comment]
Thank you for answering @elektrolitr, and yes, I will close this issue.

**Comment by EinSchwerd** [comment]
I removed and re-downloaded the custom component, then reconfigured and I am now facing a different issue:
`Logger: homeassistant.config_entries`
`Source: config_entries.py:402`
`First occurred: 07:54:54 (2 occurrences)`
`Last logged: 07:56:09`

`Error setting up entry HomeWhiz for HomeWhiz`
`Traceback (most recent call last):`
`  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup`
`    result = await component.async_setup_entry(hass, self)`
`             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "/config/custom_components/HomeWhiz/__init__.py", line 34, in async_setup_entry`
`    hass.config_entries.async_setup_platforms(entry, [Platform.SENSOR])`
`    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`

Any suggestions?
