### ISSUE TITLE
Dacite issue

### ISSUE THREAD

**Issue by GeorgKlaussner** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#175]
This integration causes issue with other standard integrations in Homeassistant. The devs mentioned the dacite version, which should be updated.

**Comment by TechHummel** [comment]
Thanks for the report @GeorgKlaussner. Do you have a link to where this was discussed?

**Comment by GeorgKlaussner** [comment]
They are discussing it in [here](https://github.com/humbertogontijo/homeassistant-roborock/issues/510)

Installing Homewhiz integration breaks integrations like roborock after restarting the server. Uninstalling homewhiz and rebooting fixes the issue.

I hope this helps.

**Comment by TechHummel** [comment]
Thanks for the link!
As you can see in the [manifest ](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/blob/main/custom_components/homewhiz/manifest.json), we actually don't specify a version for dactite. Therefore, I will close this issue 👍

**Comment by GeorgKlaussner** [comment]
Then its something else. Everytime i install this integration it breaks others.
