### ISSUE TITLE
anyone having problems connecting through wifi? (Grundig induction hob)

### ISSUE THREAD

**Issue by elmystico** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#178]
Hi guys
I've got this Grundig induction hob which was working in HomeWhiz but always was kinda useless.
And then I've commited HA in my home but couldn't connect hob with the app anymore. It seems connecting to wifi but can't register within homewhiz app afterwards.
I thouth that maybe it's because openwrt router update at some time in the past but frankly no idea. Tried many wifi router configurations.
Anyone had this issue?
I've got Beko fridge connected thru wifi no problem pairing with HomeWhiz the same router.

**Comment by TechHummel** [comment]
Sorry for my late response. I opened up discussions here on GitHub so that topics can be discussed without opening issues 😄
