### ISSUE TITLE
Beko Waschmaschine keine Verbindet 

### ISSUE THREAD

**Issue by disclaimer01** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#182]
Hallo, mir wird die Waschmaschine in HA angezeigt,  aber die Sensoren geben keine Daten auf.
Auf einem Handy konnte ich einen Waschvorgang starten. 

Ich möchte später die Waschmaschine bei günstigen Strom automatisch starten lassen geht das überhaupt? 
Oder ist es einfacher an der Maschine ein Startvorwahl (Startverzögerung) einzustellen?

**Comment by TechHummel** [comment]
I think this is a duplicate of #183.
Regarding your question: While it is possible to control certain features, I'm not sure if starting will work. Is this supported in the original app?
