### ISSUE TITLE
Unknown state for BEKO washing machine

### ISSUE THREAD

**Issue by cnecrea** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#185]
Hi there,

I've also discovered that my BEKO B5WFU78435WB (7002340002) it has one new task that HomeWhiz doesn't not recognize. Right now the washing machine is "washing" but Home Assistant shows "unknown" task

How can I get the "tasks" from HomeWhiz phone app and see what's wrong?

<img width="546" alt="image" src="https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/48139709/23478468-c022-4ad7-a8c3-613296e6db5e">

**Comment by TechHummel** [comment]
Hi 👋,
could you share some debug logs?
Thanks!

**Comment by cnecrea** [comment]
Hi there,

Yes, here we go:  [homewhizz.log](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/files/13891499/homewhizz.log)

**Comment by Mikescotland** [comment]
Pretty much something isn't right in my washer_substate too. I've got washer-dryer and old versions of your Addon worked fine (before the breaking change).
Version 0.6 randomly was changing washer_substate but mainly stayed in "remove the laundry".
The latest version is constantly stuck on "washing finished, remove laundry" while all other options and sensors are flawless. See the screenshot
![Uploading Screenshot_20240125_144822.jpg…]()

**Comment by Mikescotland** [comment]
F999 9226 1840 7970 4793 37
It works correctly if I unplug the washing machine from the mains and plug it in again. For the following washing then the substate is reported fine, another washing after this fine and then after a day I do another washing and the substate is always "remove laundry".
I haven't used the app for a year and I am unable to test if the app reads the same status as.. For some reasons the app doesn't let you see the progress of washing unless you chose "download program". It used to do it before, I'm sure.

**Comment by TechHummel** [comment]
@cnecrea I decoded all the messages from your logs.

```
State: None
Substate: None
State: program_wool_handwash
Substate: None
State: program_mix
Substate: None
State: program_mix
Substate: None
State: program_drum_clean
Substate: None
State: program_drum_clean
Substate: washer_substate_program_started
State: program_drum_clean
Substate: washer_substate_program_started
State: program_drum_clean
Substate: washer_substate_washing
State: program_drum_clean
Substate: washer_substate_washing
State: program_drum_clean
Substate: washer_substate_washing
State: program_drum_clean
Substate: washer_substate_prewash
State: program_drum_clean
Substate: washer_substate_prewash
State: program_drum_clean
Substate: washer_substate_prewash
State: program_drum_clean
Substate: washer_substate_prewash
State: program_drum_clean
Substate: None
State: program_drum_clean
Substate: None
State: program_drum_clean
Substate: None
State: program_drum_clean
Substate: None
State: program_drum_clean
Substate: None
State: program_drum_clean
Substate: washer_substate_paused
State: program_delicates
Substate: None
State: program_wool_handwash
Substate: None
State: program_eco_40_60
Substate: None
State: program_cottons
Substate: None
State: None
Substate: None
```
The only "None" states, which should translate to unknown in Home assistant, are at the beginning and at the end. And those should be, according to the app, washing?

**Comment by TechHummel** [comment]
I'll close this issue for now as there haven't been any updates in some time.
