### ISSUE TITLE
Weird letters

### ISSUE THREAD

**Issue by Smandurlo** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#202]
I have a beko washing machine. My system is in Italian and I got a few of strange letters used for ' à è °C and so on. You got the point :-)

Some of them I was able to replace inside HA, but others I cannot find the way.

It happens for some input select options, like eco wash and others.

Here is an image to explain it

How to correct them?
Thanks!

**Comment by Smandurlo** [comment]
![Screenshot_2024-02-28-09-20-20-419_io homeassistant companion android-edit](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/36647269/b1962804-6e65-4f5f-b61b-c7085797a398)

**Comment by Smandurlo** [comment]
Thanks for the feedback. I can see some errors: Lo sportello \u00c3\u00a8 aperto
it should be lo sportello è aperto
But sportello aperto is fine and there is not the problem with the " è "

Also   "temperature_20": "20\u00b0C",

And many others. 

Those backslash and letters/numbers are odd.

I can see many of them when there are à è ì ò ù (we use them) and °

I could correct the sentences to remove the accents and to make them shorter keeping the meaning, but I don't know how to do it :-)

**Comment by TechHummel** [comment]
All the words that are starting with \u are actually unicode characters. Your temperature 20, for example, contains a [degree symbol](https://www.compart.com/en/unicode/U+00B0).

Usually, if you wanted to contribute translations, you would open a pull request. If this is too complicated however, you can just download the file, fix all errors and paste the content here in the chat 😄
You can also use any special character you want, I will use a script to automatically convert them to the \u words (as encouraged for Homeassistant).

**Comment by Smandurlo** [comment]
not that difficult, I will try it soon. I am not in a hurry for that... but I am in a hurry for my work with a very close deadline :-p

I will try to use shorter and easy sentences without unicode characters, for example " è " (it means "is") can be avoided: "Lo sportello è aperto" (the door is open) = "sportello aperto" (door open). You got the point.

thanks again for your work

**Comment by TechHummel** [comment]
Yes, no need to rush. But there is also no need to avoid special characters, it's not a problem.
