### ISSUE TITLE
Washing Machine via Cloud does not retrieve values (unavailable)

### ISSUE THREAD

**Issue by ftorredeflot** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#207]
hi,

I deployed the integration using HACS and I connected my bluetooth washer via Bluetooth proxy integrated on a Shelly device

the connection works successfully but doesn't allow me to do anything and doesn't get any info.

![gh1](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/22221838/71722a76-3e03-4970-9a8f-b6391f1ac751)

I checked the logs and i find this

``` 
2024-03-25 18:49:27.506 DEBUG (MainThread) [custom_components.homewhiz] Sensors: ['state', 'washer_program', 'sub_state', 'washer_temperature', 'washer_spin', 'washer_fast_plus', 'custom_duration_level', 'washer_extra_rinse_count', 'delay_start#0', 'washer_duration', 'washer_remaining', 'washer_delay', 'delay_start_time#0', 'settings_volume']

2024-03-25 18:49:27.506 DEBUG (MainThread) [custom_components.homewhiz] Entities: {'state': <entity unknown.unknown=unknown>, 'washer_program': <entity unknown.unknown=unknown>, 'sub_state': <entity unknown.unknown=unknown>, 'washer_temperature': <entity unknown.unknown=unknown>, 'washer_spin': <entity unknown.unknown=unknown>, 'washer_fast_plus': <entity unknown.unknown=unknown>, 'custom_duration_level': <entity unknown.unknown=unknown>, 'washer_extra_rinse_count': <entity unknown.unknown=unknown>, 'delay_start#0': <entity unknown.unknown=unknown>, 'washer_duration': <entity unknown.unknown=unknown>, 'washer_remaining': <entity unknown.unknown=unknown>, 'washer_delay': <entity unknown.unknown=unknown>, 'delay_start_time#0': <entity unknown.unknown=unknown>, 'settings_volume': <entity unknown.unknown=unknown>}

```

I don't know if i'm doing something wrong, or the connection is fake.

if you need more logs, i'll be glad to provide them.

Thanks ,

Ferran Torredeflot

**Comment by ftorredeflot** [comment]
I upgraded to version 0.5.4, and the issue persists, on the logs I don't see any relevant.

**Comment by TechHummel** [comment]
Hi 👋
If there are no Bluetooth errors in the logs, it is unlikely this is an issue with the connection. If you could, please provide as many logs as possible.

**Comment by ftorredeflot** [comment]
hi
I have attached some logs
thanks for your response :)

[logs.txt](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/files/15074469/logs.txt)

**Comment by TechHummel** [comment]
Hi 👋 
Could you try again with the changes in this branch and share your logs?
https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/tree/207-entity-unknownunknown%3Dunknown-values
Thanks 😊

**Comment by ftorredeflot** [comment]
thanks to you, here you have the logs but i didn't see anything interesting
[new_logs.txt](https://github.com/user-attachments/files/15917909/new_logs.txt)

**Comment by TechHummel** [comment]
Could you try the code in this PR? 😊 
https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/230

**Comment by Exc1usive** [comment]
@TechHummel 
Hello, i was trying this version, now i can see entities but can`t control it :(

**Comment by TechHummel** [comment]
Thanks for the feedback. Is there anything in the logs?

**Comment by Exc1usive** [comment]
> Is there anything in the logs?

yes, this my log when i trying to send some kind of commands
![image](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/33939398/f09b8230-7a1b-450b-865f-81a6157122e1)

**Comment by TechHummel** [comment]
And controlling works fine via the app?
With my Bluetooth washing machine, I can only control it when it's in a special mode.

**Comment by Exc1usive** [comment]
> And controlling works fine via the app? With my Bluetooth washing machine, I can only control it when it's in a special mode.

yes, i have the same, i was trying switch some states with native app and integration at the same time and my native app works fine.

**Comment by ftorredeflot** [comment]
hi, I keep the same issue I attach logs 
[logs24june.txt](https://github.com/user-attachments/files/15960527/logs24june.txt)

**Comment by ftorredeflot** [comment]
my washing machine works with bluetooth

**Comment by ftorredeflot** [comment]
Ok, I tried avoiding shelly as Bluetooth proxy and it works perfect

**Comment by Bastian007** [comment]
I am facing the same issue. In HomeWhiz App I can see the current status of my washing maschine. 
Adding my mashine via integration mode _Cloud_, the device is detected and added, but all sensors are unavailable. 

Integration mode _Bluetooth_ doesn't find any device. What Bluetooth scanner mode would be the right mode? Active or Passive?

**Comment by Exc1usive** [comment]
After installing the latest version, everything works fine for me. I can connect my washing machine, check and change statuses.
