### ISSUE TITLE
All entities are now Unavailable

### ISSUE THREAD

**Issue by GigiPompieru** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#214]
Hi, after updating to 2024.5.0 all the entities for my Dishwasher have become unavailable.

The strange thing is that there are no errors in the logs, even after enabling debug for the integration, or maybe I'm looking in the wrong place.

The only thing related to HomeWhiz is:
```
Detected that custom integration 'homewhiz' calls async_write_ha_state from a thread at custom_components/homewhiz/cloud.py, line 231: self.async_set_updated_data(data), please report it to the author of the 'homewhiz' custom integration
```
but that is just a warning and should not affect the addon.

I have removed the addon from HACS and re-added. It works fine, logins, shows the device to add, but then it pulls no data.

It has been working without issues prior to 5.0.

**Comment by yusufbogatepe** [comment]
All entities become unavailable after 2024.5.0 core update. I also have your error with below.

`Entity None (<class 'custom_components.homewhiz.climate.HomeWhizClimateEntity'>) implements HVACMode(s): cool, auto, dry, heat, fan_only, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature.`

**Comment by paksiali** [comment]
2024.5.0 core update then i get the same error

Entity None (<class 'custom_components.homewhiz.climate.HomeWhizClimateEntity'>) implements HVACMode(s): cool, auto, dry, heat, fan_only, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues

**Comment by Croft5** [comment]
I am also finding that everything is unavailable

**Comment by TechHummel** [comment]
Hi everyone 👋
I started investigating the warning, but I am not sure how to fix it.
For the other climate related comments, please check #216 .

**Comment by BlackiceSpain** [comment]
> Hi everyone 👋 I started investigating the warning, but I am not sure how to fix it. For the other climate related comments, please check #216.

I have realized that, althought there is "no communication", there is actually some communication:

With a call service node I am being able to set_temperature of the AC with the following expression:
`{"temperature": $number($entities('input_number.t_ac_max_bnh_0').state)}`

**Comment by elektrolitr** [comment]
I've also encountered this issue and find in the log the only suspicious entry (I had to set log to "debug" level to see such details):

`2024-05-11 21:37:35.367 DEBUG (MainThread) [custom_components.homewhiz] Entities: {'state': <entity unknown.unknown=unknown>, 'dishwasher_program': <entity unknown.unknown=unknown>, 'sub_state': <entity unknown.unknown=unknown>, 'dishwasher_delay': <entity unknown.unknown=unknown>, 'dishwasher_duration': <entity unknown.unknown=unknown>, 'dishwasher_remaining': <entity unknown.unknown=unknown>, 'setting_detergent_type': <entity unknown.unknown=unknown>, 'dishwasher_rinse_aid_level': <entity unknown.unknown=unknown>, 'dishwasher_liquid_detergent_level': <entity unknown.unknown=unknown>, 'dishwasher_water_hardness': <entity unknown.unknown=unknown>}`

The rest of the log looks as normal, The Homewhiz component seems to connect correctly to the AWS server. There's an update each minute and the packet looks around the same as usual.

**Comment by mgolaszewski93** [comment]
Any News? Only bluetooth device works good.

**Comment by T-z3P** [comment]
Same issue here.

**Comment by dudzio12** [comment]
+1

**Comment by teqali** [comment]
1+

**Comment by GigiPompieru** [comment]
> Hi everyone 👋 I started investigating the warning, but I am not sure how to fix it. For the other climate related comments, please check #216.

any update on this? is there still hope?

**Comment by es3nric** [comment]
+1

**Comment by TechHummel** [comment]
> any update on this? is there still hope?

There's always hope 😉 
But: The integration works fine for me (washing machine with Bluetooth), so I am not sure what's going on, and I am unable to debug this properly. Maybe someone could share their credentials with me? hv63f5xo@anonaddy.me

**Comment by seyu77** [comment]
There is a problem in 2024.5.0 and later versions. For this reason, I cannot update the Homeassistant version.

**Comment by EdSpatariu** [comment]
> > any update on this? is there still hope?
> 
> There's always hope 😉 But: The integration works fine for me (washing machine with Bluetooth), so I am not sure what's going on, and I am unable to debug this properly. Maybe someone could share their credentials with me? [hv63f5xo@anonaddy.me](mailto:hv63f5xo@anonaddy.me)

I shared the credentials with you via email.
Thank you.

**Comment by TechHummel** [comment]
Hi all 👋 
can you test if everything is working now with the new beta release v0.5.5-beta?
Thanks 😊

**Comment by Croft5** [comment]
Yes it is, thank you 😊

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yusufbogatepe** [comment]
Hi again,
Integration works fine. But gives an error like this when i try to turn_on.
![Screenshot 2024-06-15 at 00 04 57](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/45658946/3cbae1f0-2ed9-4c42-a172-709e0698dc42)

**Comment by TechHummel** [comment]
Was it working before?
Anyway: Could you create a new issue and attach logs? Thanks!

**Comment by yusufbogatepe** [comment]
> Was it working before? Anyway: Could you create a new issue and attach logs? Thanks!

Yes it was. I added the code and tried. It worked with that feature. But the problem is every time I opened the AC it's changing to heating mode. It doesn't matter what mode(cool,dry,heat,etc.) i left it before. This was never happened before before this "unavailable" problem for cloud devices.

I have Midea AC integration as well and never experienced this problem.

**Comment by EdSpatariu** [comment]
Hi all,

I confirm everything works just fine.
Thank you @TechHummel for your quick fix.

**Comment by GigiPompieru** [comment]
> Hi all 👋 can you test if everything is working now with the new beta release v0.5.5-beta? Thanks 😊
> 
> And thanks again for sharing the credentials @EdSpatariu , that was very helpful! 👍

Yes, works now. Thank so much for the support!

**Comment by T-z3P** [comment]
I can confirm it works with Grundig GREPE120 AC.

**Comment by dudzio12** [comment]
@TechHummel Working for Beko Dryer too <3

**Comment by seyu77** [comment]
> Hi all 👋 can you test if everything is working now with the new beta release v0.5.5-beta? Thanks 😊
> 
> And thanks again for sharing the credentials @EdSpatariu , that was very helpful! 👍

Thank you. Arçelik air conditioners are currently working without any problems.

**Comment by es3nric** [comment]
Hi, working again with Beko Dishwasher.
Thank you very much!
