### ISSUE TITLE
Warning about ClimateEntityFeature FeatureFlags missing after 2024.5.0 core update

### ISSUE THREAD

**Issue by paksiali** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#216]
2024.5.0 çekirdek güncellemesinden sonra tüm varlıklar kullanılamaz hale gelir.
error

`Entity None (<class 'custom_components.homewhiz.climate.HomeWhizClimateEntity'>) implements HVACMode(s): cool, auto, dry, heat, fan_only, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues`

**Comment by TechHummel** [comment]
You can test this and see if the message disappears: https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/217

**Comment by elmystico** [comment]
I've tried using new code but got non-working.
The thing is that without new code you dont have updates to entities automatically but you can force them by changing something in config of entity (tag , comment) and press update. Also it seems that commands somehowe go out succesfully.
But with your new changes my result is "nothing works" unfortunatelly.
