### ISSUE TITLE
BEKO Washing machine no longer available

### ISSUE THREAD

**Issue by larsschweier** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#218]
The only error I find in the logs is:

`Detected that custom integration 'homewhiz' calls async_write_ha_state from a thread at custom_components/homewhiz/cloud.py, line 231: self.async_set_updated_data(data), please report it to the author of the 'homewhiz' custom integration`

**Comment by xGeKox** [comment]
Me too

**Comment by thomasboegl1** [comment]
Duplicate #214
