### ISSUE TITLE
Kullanım dışı

### ISSUE THREAD

**Issue by Teknoline** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#220]
Büyük bir heyecanla kurdum. Varlıkların hepsinde kullanım dışı yazıyor. Bunu nasıl düzeltebilirim

**Comment by paksiali** [comment]
2024.5.0 güncellemesinden sonra herkezin kullanım dışı hala düzeltemediler 1 aydır yani düzelecek gibide durmuyor sanki

**Comment by Teknoline** [comment]
anladım. teşekkürler

**Comment by TechHummel** [comment]
I'll close this as we only support issues in English, sorry.
