### ISSUE TITLE
climate.turn_on not supported

### ISSUE THREAD

**Issue by yusufbogatepe** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#223]
After beta patch 0.5.5 arrived I could add my cloud devices again. But when i try to use my AC from dashboard, It gives an error that climate.turn_on not supported.

I think your climate.py supported features section missing "ClimateEntityFeature.TURN_ON" feature. Because I added locally and it worked. It was working before "unavailable" devices problem. And there is another bug happened when I added turn_on feature. It doesn't matter which mode(COOL,DRY,HEAT,etc.) I turned_off the AC, when I turned on its always changing to "HEAT" mode not the latest one I turned off.

I have Midea Integration for my Midea AC. I never experienced this problem before. So I think there is something bugging around :).

![Screenshot 2024-06-15 at 00 04 57](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/45658946/eb5e3d98-5d49-45fa-a4b8-7cf3d3f3d0d9)

**Comment by TechHummel** [comment]
Thanks for reporting!
Could you try the code in this PR: https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/pull/224 
Instead of default to HEAT, it should now default to HEAT_COOL. 
And, if you turn off the AC, the integration should memorise your last mode and use that mode when you turn on your AC again.

**Comment by yusufbogatepe** [comment]
> Thanks for reporting! Could you try the code in this PR: #224 Instead of default to HEAT, it should now default to HEAT_COOL. And, if you turn off the AC, the integration should memorise your last mode and use that mode when you turn on your AC again.

Thanks for the fix. Everything is working correctly right now.

**Comment by TechHummel** [comment]
Does the HVAC memory also work as expected?

**Comment by yusufbogatepe** [comment]
> Does the HVAC memory (same mode as before turning it off) also work as expected?

Yes it is.
