### ISSUE TITLE
Grinding AC stop working on new update 

### ISSUE THREAD

**Issue by home89c3** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#225]
Hi, afthe the new update the integration stop working   I try to downgrade but same unavailable.
![Screenshot_20240616-162650](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/111180553/4e8c6919-3c8d-446f-8e3e-30007038ee0f)
Any ideea way this happenend.
Thx!

**Comment by TechHummel** [comment]
Can you installing the beta version?

**Comment by home89c3** [comment]
> Can you installing the beta version?

Yes I install the last version 0.5.4. I try also an old backup on the entire ha Sistem.  But same...

**Comment by TechHummel** [comment]
No, I said beta version 😉 
https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/releases/tag/v0.5.5-beta

**Comment by home89c3** [comment]
Ok, many thanks.! Now work on beta
