### ISSUE TITLE
Extraction fan not listed as supported device + how to buy you a beer?

### ISSUE THREAD

**Issue by bjacobse** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#227]
Thank you for making the extraction fan working for me, 
You need to have a paypal account to receive a recognition, so I can buy you a beer

Remember to upsate the front page, to include supported device Extraction Fan + contribution how to buy you a beer

**Comment by TechHummel** [comment]
Thank you for your kind words and your willingness to contribute financially 😊. 
However, I'm not accepting money (most of the code wasn't written by mec and it's a fun hobby for me).
I'll leave the issue open for updating the README. 😄
