### ISSUE TITLE
AC unavailable with 2024.10

### ISSUE THREAD

**Issue by mauriziov** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#241]
Hello, starting from October Home Assistant Update the AC has become unavailable. 

Below the HA log: 
```
Registratore: homeassistant.config_entries
Fonte: /usr/src/homeassistant/homeassistant/config_entries.py:678
Prima occorrenza: 5 ottobre 2024 alle ore 11:31:33 (3 occorrenze)
Ultima registrazione: 13:33:38

Error setting up entry Condi cameretta for homewhiz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 36, in async_setup_entry
    return await setup_cloud(entry, hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/__init__.py", line 99, in setup_cloud
    ] = HomewhizCloudUpdateCoordinator(hass, ids.appId, cloud_config, entry)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/cloud.py", line 68, in __init__
    from awscrt import mqtt
  File "/usr/local/lib/python3.12/site-packages/awscrt/mqtt.py", line 9, in <module>
    import _awscrt
ImportError: Error loading shared library /usr/local/lib/python3.12/site-packages/_awscrt.abi3.so: Exec format error
```

**Comment by TechHummel** [comment]
Thanks for your report!
Could you give me the output of `pip freeze`?

**Comment by mauriziov** [comment]
Hello, thank you for your reply.
It should be the pip freezer output:

upb-lib==0.5.8
upcloud-api==2.5.1
update-checker==0.18.0
uplink==0.9.7
uplink-protobuf==0.1.0
uritemplate==4.1.1
url-normalize==1.4.3
urllib3==1.26.20
usb-devices==0.4.5
uv==0.4.15
uvcclient==0.12.1
vacuum-map-parser-base==0.1.3
vacuum-map-parser-roborock==0.1.2
validators==0.34.0
vallox_websocket_api==5.3.0
vehicle==2.2.2
velbus-aio==2024.7.6
venstarcolortouch==0.19
vilfo-api-client==0.5.0
vincenty==0.1.4
virtualenv==20.27.0
vobject==0.9.8
voip-utils==0.1.0
volkszaehler==0.4.0
voluptuous==0.15.2
voluptuous-openapi==0.0.5
voluptuous-serialize==2.6.0
volvooncall==0.10.3
vsure==2.6.6
vtjp==0.2.1
vulcan-api==2.3.2
vultr==0.1.2
wakeonlan==2.1.0
wallbox==0.7.0
warrant-lite==1.0.4
watchdog==2.3.1
waterfurnace==1.1.0
wcwidth==0.2.13
weatherflow4py==1.0.6
webcolors==24.8.0
webencodings==0.5.1
webmin-xmlrpc==0.0.2
websocket-client==1.8.0
websockets==13.1
weheat==2024.9.23
Werkzeug==3.0.6
wheel==0.44.0
whirlpool_sixth_sense==0.18.8
whois==0.9.27
wiffi==1.1.2
wirelesstagpy==0.8.1
wled==0.20.2
wolf_comm==0.0.15
wrapt==1.16.0
WSDiscovery==2.0.0
wsproto==1.2.0
wyoming==1.5.4
accuweather==3.0.0
acme==2.10.0
adax==0.4.0
Adax-local==0.1.5
adb-shell==0.4.4
adext==0.4.3
adguardhome==0.7.0
advantage-air==0.4.4
AEMET-OpenData==0.5.4
aenum==3.1.15
afsapi==0.2.7
agent-py==0.0.23
aio-geojson-client==0.20
aio-geojson-generic-client==0.4
aio-geojson-geonetnz-quakes==0.16
aio-geojson-geonetnz-volcano==0.9
aio-geojson-nsw-rfs-incidents==0.7
aio-geojson-usgs-earthquakes==0.3
aio-georss-client==0.13
aio-georss-gdacs==0.10
aioairq==0.3.2
aioairzone==0.9.5
aioairzone-cloud==0.6.6
aioambient==2024.8.0
aioapcaccess==0.4.2
aioaquacell==0.2.0
aioaseko==1.0.0
aioasuswrt==1.4.0
aioautomower==2024.10.0
aioazuredevops==2.2.1
aiobafi6==0.9.0
aiobotocore==2.13.1
aiocache==0.12.3
aiocoap==0.4.11
aiocomelit==0.9.0
aioconsole==0.8.0
aiodhcpwatcher==1.0.2
aiodiscover==2.1.0
aiodns==3.2.0
aiodukeenergy==0.2.2
aioeafm==0.1.2
aioeagle==1.1.0
aioecowitt==2024.2.1
aioelectricitymaps==0.4.0
aioemonitor==1.0.5
aioesphomeapi==27.0.0
aiofile==3.9.0
aiofiles==24.1.0
aioflo==2021.11.0
aioftp==0.21.3
aiogithubapi==24.6.0
aioguardian==2022.7.0
aiohappyeyeballs==2.4.3
aioharmony==0.2.10

**Comment by mauriziov** [comment]
Thanks for you reply, attached the complete output of pip freeze
[pip_freeze.txt](https://github.com/user-attachments/files/17534776/pip_freeze.txt)

**Comment by TechHummel** [comment]
I'm not sure why you are seeing this error, but my guess is that this might be related to an invalid awscrt wheel built by homeassistant or that the wrong version (for a different architecture) of awscrt is installed.
This is a similar issue: https://github.com/home-assistant/core/issues/114779

You can try to follow the guide in this issue and install and/or build the awscrt library yourself: https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues/236

**Comment by mauriziov** [comment]
I had the problem with awsiotsdk the first time I installed the integration, I solved It following that guide. In the lasts home assistant release, starting from August or maybe September, the awsiotsdk was already installed so I didn't build the library manually. Few minutes ago I tries to install It but the library Is already installed.

**Comment by mauriziov** [comment]
@TechHummel hello, just to inform you that the AC was become available with the november release of home assistant. Thanks
