### ISSUE TITLE
Status unavailable

### ISSUE THREAD

**Issue by remikk77** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#60]
Hi

I add washing machine and addon get entity but all are unavailable.
What can I do?

**Comment by TechHummel** [comment]
Did you try select or start a washing machine program?

**Comment by rowysock** [comment]
Please make sure your phone isn't connected to the washing machine.

**Comment by remikk77** [comment]
Phone is disconnected. I turned off Bluetooth also to be sure.
Program was started and nothing change.

**Comment by remikk77** [comment]
Name of washing machine was read from previous setting which was put in app on phone. 


![image](https://user-images.githubusercontent.com/120499436/207792757-13edc0a3-54fd-4c8f-9779-8de3212e9476.png)

**Comment by rowysock** [comment]
Can you share the logs?

**Comment by remikk77** [comment]
Which? On integration I have information that no logs

![image](https://user-images.githubusercontent.com/120499436/207827871-e2c55b7e-63f2-445b-a2a9-8bd5d01850ef.png)

**Comment by rowysock** [comment]
Settings -> System -> Logs
https://www.home-assistant.io/integrations/system_log/

**Comment by remikk77** [comment]
Unfortunately I don't see  anything. I tried restart washing machine now and check logs

Wyświetl cały log
2022-12-15 11:26:35.620 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-15 11:26:35.621 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mikrotik_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-15 11:26:35.627 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-15 11:26:35.628 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homewhiz which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-15 11:26:35.630 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by rowysock** [comment]
@remikk77 Please refer to the newly added README section: https://github.com/rowysock/home-assistant-HomeWhiz#retrieve-integration-logs
@TechHummel thank you for this section

**Comment by remikk77** [comment]
I attach log[](url)
[home-assistant_2022-12-15T18-42-24.758Z.log.zip](https://github.com/rowysock/home-assistant-HomeWhiz/files/10239768/home-assistant_2022-12-15T18-42-24.758Z.log.zip)

**Comment by rowysock** [comment]
@remikk77 I've removed the logs you attached, as those contain your personal info.

In the logs, I cannot see anything about connecting to the actual appliance. My guess is that your washing machine is too far away and Home Assistant is not detecting it

**Comment by remikk77** [comment]
Thanks. This HA is for testing now.
Beko is located under HA, one floor. But i think i can move for twsting HA near washing machine. I let you know, i need some time for that.

**Comment by TechHummel** [comment]
@rowysock Which kind of information was included? We should add a warning to the readme 😨 
@remikk77 An ESPHome Bluetooth Proxy might be a long term alternative (that's what I am using)

**Comment by rowysock** [comment]
Nothing crazy like a credit card pin number, or Gmail password, but user names and an approximate location. I think many would consider this personal info not to be shared on a public forum

**Comment by rowysock** [comment]
@TechHummel If you know how to easily extract the logs only for this integration this would be very helpful

**Comment by TechHummel** [comment]
The only idea I have would to be increase the default log level to error 😢

**Comment by remikk77** [comment]
I move device with HA and Bluetooth near washing device. About 1-2 meters. 
rowysock I've send logs to your email.

**Comment by remikk77** [comment]
Status was unanavailable. But I think that problem was with Bluetooth added to Virtualbox. I check everything again I saw that bleutooth device was not available in my HA. Now I readd everything and status is available


![image](https://user-images.githubusercontent.com/120499436/208311470-cc348027-592c-4cd2-a4c5-b7084d5f82f1.png)

**Comment by tnrclkr** [comment]
When im connected to washing machine at home, all works fine. it just says unavailable when im not at home or connected to the device. i guess this is normal behaviour because app just gets info from machine when connected BT. 

What im trying to do now; if i can connect Washing Machine to Raspberry bluetooth and create a network to my mobile phone over internet it may start to work when im not at home.

**Comment by rowysock** [comment]
@remikk77 I'm closing this issue then. Good to hear it's working for you
@tnrclkr you can connect to your local Home Assistant as described here: https://www.home-assistant.io/docs/configuration/remote/
I highly recommend the easy path of buying [Home Assistant Cloud](https://www.nabucasa.com/) subscription and supporting this wonderful project
